"""add payment_intent_id to orders

Revision ID: 5b5055aa952e
Revises: ede450eb064f
Create Date: 2026-09-21 13:40:14.856851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b5055aa952e'
down_revision: Union[str, Sequence[str], None] = 'ede450eb064f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_intent_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_intent_id')
    # ### end Alembic commands ###
